export default {
    CREATE_JOB_TITLE:"Create Job",
    POP_UP1_BUTTON_TITLE:"Next",
    POP_UP2_BUTTON_TITLE:"Save",
    POP_UP_TITLE:"Create a job",
    POP_UP1_SUBTITLE:"Step 1",
    POP_UP1_INPUT1_TITLE:"Job title",
    POP_UP1_INPUT2_TITLE:"Company name",
    POP_UP1_INPUT3_TITLE:"Industry",
    POP_UP1_INPUT4_TITLE:"Location",
    POP_UP1_INPUT5_TITLE:"Remote type",
    POP_UP1_INPUT1_PLACEHOLDER:"ex. UX/UI Designer",
    POP_UP1_INPUT2_PLACEHOLDER:"ex. Google",
    POP_UP1_INPUT3_PLACEHOLDER:"ex. Information Technology",
    POP_UP1_INPUT4_PLACEHOLDER:"ex. Chennai",
    POP_UP1_INPUT5_PLACEHOLDER:"ex. In-office",
    POP_UP2_SUBTITLE:"Step 2",
    POP_UP2_INPUT1_TITLE:"Experience",
    POP_UP2_INPUT2_TITLE:" ",
    POP_UP2_INPUT3_TITLE:"Salary",
    POP_UP2_INPUT4_TITLE:" ",
    POP_UP2_INPUT5_TITLE:"Total employee",
    POP_UP2_INPUT1_PLACEHOLDER:"Minimum",
    POP_UP2_INPUT2_PLACEHOLDER:"Maximum",
    POP_UP2_INPUT3_PLACEHOLDER:"Minimum",
    POP_UP2_INPUT4_PLACEHOLDER:"Maximum",
    POP_UP2_INPUT5_PLACEHOLDER:"ex. 100",
    POP_UP_RADIO_TITLE:"Apply type",
    POP_UP_RADIO_OPTION1:"Quick apply",
    POP_UP_RADIO_OPTION2:"External apply",
    JOB_TILE_BUTTON_APPLY_NOW:"Apply Now",
    JOB_TILE_BUTTON_EXTERNAL_APPLY:"External Apply"
}